import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Bot, Zap, DollarSign, ShieldCheck, MessageSquare } from "lucide-react";
import botImage from "@/assets/bot-trading.jpg";

const BotTrading = () => {
  const benefits = [
    {
      icon: Zap,
      title: "24/7 Automated Trading",
      description: "Let AI-powered bots trade for you around the clock, never miss an opportunity.",
    },
    {
      icon: ShieldCheck,
      title: "Security Verified",
      description: "All bots undergo rigorous security audits before approval on our platform.",
    },
    {
      icon: DollarSign,
      title: "Revenue Share Program",
      description: "Bot owners earn 30% of all profits generated by their bots on user accounts.",
    },
  ];

  return (
    <section id="bots" className="py-16 bg-secondary/30">
      <div className="container mx-auto px-4">
        <div className="grid lg:grid-cols-2 gap-8 items-center">
          {/* Bot Image */}
          <div className="relative animate-fade-in order-2 lg:order-1">
            <div className="absolute inset-0 bg-gradient-primary opacity-20 blur-3xl"></div>
            <img 
              src={botImage} 
              alt="Automated trading bot interface with AI indicators" 
              className="relative rounded-2xl shadow-glow border border-primary/20 w-full max-w-md mx-auto"
            />
          </div>
          
          {/* Content */}
          <div className="space-y-8 animate-slide-up order-1 lg:order-2">
            <div>
              <div className="inline-flex items-center gap-2 bg-accent/10 border border-accent/20 rounded-full px-4 py-2 mb-4">
                <Bot className="h-4 w-4 text-accent" />
                <span className="text-sm text-muted-foreground">Automated Trading Platform</span>
              </div>
              
              <h2 className="text-4xl md:text-5xl font-bold mb-4">
                <span className="text-foreground">Trade with</span>
                <br />
                <span className="bg-gradient-primary bg-clip-text text-transparent">AI-Powered Bots</span>
              </h2>
              <p className="text-xl text-muted-foreground">
                Leverage advanced algorithms and machine learning to maximize your trading potential. Our platform supports verified third-party bots with a unique revenue-sharing model.
              </p>
            </div>
            
            <div className="space-y-4">
              {benefits.map((benefit, index) => (
                <Card 
                  key={index}
                  className="p-6 bg-card border-border hover:border-primary/50 transition-all duration-300 hover:shadow-glow"
                >
                  <div className="flex gap-4">
                    <div className="w-12 h-12 rounded-lg bg-gradient-primary p-3 shrink-0">
                      <benefit.icon className="w-full h-full text-primary-foreground" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold mb-1 text-foreground">{benefit.title}</h3>
                      <p className="text-muted-foreground">{benefit.description}</p>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
            
            {/* Bot Owner CTA */}
            <Card className="p-6 bg-gradient-to-br from-accent/10 to-accent/5 border-accent/30">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-lg bg-gradient-accent p-3 shrink-0">
                  <MessageSquare className="w-full h-full text-accent-foreground" />
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-bold mb-2 text-foreground">Bot Developers Welcome</h3>
                  <p className="text-muted-foreground mb-4">
                    Own a trading bot? Contact our support team to verify security and add your bot to our platform. Earn 30% of all profits your bot generates for other traders.
                  </p>
                  <Button variant="hero" size="lg">
                    Contact Support
                  </Button>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
};

export default BotTrading;
